// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldfbuxtzrxnrqqhqxhoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZmJ1eHR6cnhucnFxaHF4aG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NjMyNjYsImV4cCI6MjA1NDMzOTI2Nn0.S5cYLXFIc7g2YIIs0BXSsvuS4HNzkBoUkXFiuT0dh1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);